- name: "Basic playbook"
  connection: local
  hosts: kubernetes
  tasks:
  - name: "Ping"
    debug:
      msg: "{{ test }}"
  - name: Create a new DigitalOcean Kubernetes cluster in New York 1
    community.digitalocean.digital_ocean_kubernetes:
      state: present
      oauth_token: "{{ lookup('env', 'DO_API_TOKEN') }}"
      name: "{{ inventory_hostname }}"
      region: "{{ region }}"
      node_pools:
        - name: "primary-nodes"
          size: "{{ node_type }}"
          count: "{{ node_count }}"
      return_kubeconfig: yes
      wait_timeout: 600
    register: my_cluster

  - name: Show the kubeconfig for the cluster we just created
    debug:
      msg: "{{ my_cluster.data.kubeconfig }}"

  # - name: Destroy (delete) an existing DigitalOcean Kubernetes cluster
  #   community.digitalocean.digital_ocean_kubernetes:
  #     state: absent
  #     oauth_token: "{{ lookup('env', 'DO_API_TOKEN') }}"
  #     name: "{{ inventory_hostname }}-{{ region }}"


